# 处理异常数值
- numpy.ma

参考官方文档[numpy.ma](https://docs.scipy.org/doc/numpy-1.13.0/reference/maskedarray.generic.html)

In [1]:
import numpy as np

## 将数据转换成mask数据

### 按数组转换

In [3]:
x = np.arange(9).reshape([3,3])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
x_mask_array = np.ma.masked_array(x, mask=[[0,0,1]*3])
x_mask_array

masked_array(data =
 [[0 1 --]
 [3 4 --]
 [6 7 --]],
             mask =
 [[False False  True]
 [False False  True]
 [False False  True]],
       fill_value = 999999)

### 按值转换

In [12]:
x_mask_value = np.ma.masked_values(x, 0)
x_mask_value

masked_array(data =
 [[-- 1 2]
 [3 4 5]
 [6 7 8]],
             mask =
 [[ True False False]
 [False False False]
 [False False False]],
       fill_value = 0)

## 数据运算后，将mask后的数据转换成正常数据

In [14]:
x_normal =  x_mask_array
x_normal

array([[0, 1, 0],
       [3, 4, 0],
       [6, 7, 0]])